libvirt: peg at 6.0.0:
6.1.0 needs legacysupport, but even then fails due to

../../libvirt-6.1.0/src/util/virnetdevip.c:842:18: error: variable has incomplete type 'struct ifreq'
    struct ifreq ifr;
                 ^